# Generated by Django 5.2.9 on 2025-12-11 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_type', models.CharField(choices=[('standard', 'Standard Booth'), ('premium', 'Premium Booth')], max_length=32)),
                ('event_date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='booking_boo_owner_i_7dc827_idx'), models.Index(fields=['event_date'], name='booking_boo_event_d_119073_idx')],
            },
        ),
    ]
