# Generated by Django 5.2.9 on 2025-12-12 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_owner_i_7dc827_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_event_d_119073_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booth_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
